### ISSUE TITLE
Error: cannot append two different types (slice, string) (2.0.15)

### ISSUE THREAD

**Issue by cjvirtucio87** [pastdev/clconf#19]
# Problem

Running `clconf` with multiple `--yaml` switches results in an error.

# Steps to Reproduce

Create a `secrets.yml` file:

```yaml
---
jira:
  password: [OMITTED]
  url: https://jira.mitre.org/
  username: [OMITTED]
nuget:
  username: [OMITTED]
  password: [OMITTED]
resource_manager_settings:
  next_sprint_pattern: '^ASIAS ETL \\d+(:? \\((?i)next(?-i)\\))?$'
ssh:
  knownHosts: [OMITTED]
  publicKey: [OMITTED]
  privateKey: [OMITTED]
```

Create a `secrets.override.yml` file with the omitted values from `secrets.yml` _populated_.

Call `clconf` with the two files mentioned above in the order of `secrets.yml`, then `secrets.override.yml`:

```bash
clconf --yaml secrets.yml --yaml secrets.override.yml
```

# Expected Outcome

The merger of the two yaml files gets printed to the console.

# Actual Outcome

```
Error: cannot append two different types (slice, string)
Usage:
  clconf [global options] command [command options] [args...] [flags]
  clconf [command]
```

# Workarounds

`2.0.13` was the last working version, so I'll be using that for now.
