### ISSUE TITLE
Value resolution inconsistent when value specified multiple YAML files 

### ISSUE THREAD

**Issue by yoshiya8** [pastdev/clconf#7]
Below are two YAML files: `secrets.yaml` and `configMap.yaml`. The `configMap.yaml` file contains the placeholder value, `SET IN SECRETS` for usernames and passwords - these values are all specified in the `secrets.yaml` file. 

### `secrets.yaml`
```yaml
mongodb:
  service_account:
    user: mongodb-service-user
    password: mongodb-service-password
  public_account:
    user: mongo-public-user
    password: mongo-public-password
ldap:
  service_account:
    user: ldap-service-user
    password: ldap-service-password
```
### `configMap.yaml`
```yaml
mongodb:
  servers:
  - host: mongodb1.mycorp.com
    port: 27017
  - host: mongodb2.mycorp.com
    port: 27017
  - host: mongodb3.mycorp.com
    port: 27017
  service_account:
    user: SET IN SECRETS
    password: SET IN SECRETS
  public_account:
    user: SET IN SECRETS
    password: SET IN SECRETS
webapp:
  server_id: cluster1.mycorp.com
  cluster_name: Cluster 1
  external_clusters:
  - name: Cluster 2
    url: https://cluster2.mycorp.com
  - name: Cluster 3
    url: https://cluster3.mycorp.com
business_day:
  timezone: America/New_York
  start_of_day: "06:30:00"
  end_of_day: "19:30:00"
email:
  support_email: noreply@mycorp.com
  default_email_domain: "@mycorp.com"
  smtp_host: smtp-main.mycorp.com
ldap:
  provider_uri: ldaps://ldap.mycorp.com
  search_base: ou=People,dc=mycorp,dc=com
  search_filter: (uid={0})
```
I set up my `YAML_FILES` environment variable thusly:
```bash
export YAML_FILES=$(readlink -e secrets.yaml),$(readlink -e configMap.yaml)
```
When I run `clconf` the following occurs:
`clconf` *INCORRECTLY* returns `SET IN SECRETS` (from the `configMap.yaml` file) for:
* `/mongodb/public_account/password`
* `/mongodb/public_account/user`
* `/mongodb/service_account/password`
* `/mongodb/service_account/user`

`clconf` correctly returns the user/password from the `secrets.yaml` file for:
* `/ldap/service_account/password`
* `/ldap/service_account/user`
